---
- name: Provisioning mariadb
  hosts: local
  connection: local
  gather_facts: False

  tasks:
    - name: Add host to inventory
      add_host:
        name: install mariadb
        groups: mariadb
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_host: "{{ ip_addr }}"
        ansible_ssh_user: root
        ansible_ssh_port: 22
        ansible_ssh_private_key_file: "~/.ssh/{{ pubkey }}.pem"

- name: Execute tasks
  hosts: mariadb
  remote_user: root
  gather_facts: True

  vars_files:
    - include: vars/main.yml

  tasks:
    - include: tasks/main.yml