---
- name: Install nginx
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
#    - httpd-tools

# - name: Start nginx
#   service:
#     name: nginx
#     state: started
#     enabled: yes
