---
- name: Copy nginx.conf
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Copy kibana.conf
  template:
    src: templates/conf.d/kibana.conf.j2
    dest: /etc/nginx/conf.d/kibana.conf

- name: Restart nginx
  service:
    name: nginx
    state: restarted