---
#- name: Install logstash
#  yum:
#    name: https://artifacts.elastic.co/downloads/logstash/logstash-6.2.4.rpm
#    state: present
- name: Install logstash
  apt:
    name: logstash
    state: present

- name: Start logstash
  service:
    name: logstash
    state: started
    enabled: yes
