---
#- name: Install general package
#  yum:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - epel-release
#    - git
#    - nano
#    - wget
#    - python2-passlib

- name: Install general package
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - software-properties-common
    - wget
    - curl
    - nano
    - python-dev
    - python3-passlib
