---
- name: Install PHP 7.0
  hosts: local
  connection: local
  gather_facts: False

  tasks:
    - name: Add host to inventory
      add_host:
        name: Install PHP 7.0
        groups: php
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_host: "{{ ip_addr }}"
        ansible_ssh_user: root
        ansible_ssh_port: 22
        ansible_ssh_private_key_file: "~/.ssh/zerocloud"

- name: Execute tasks
  hosts: php
  remote_user: root
  gather_facts: True

  tasks: 
    - include: tasks/main.yml